### PR TITLE
Pass destination as a single `HostPort` struct 

### PR DESCRIPTION
**Pull request by lewandowski-stripe**
Additionally move the host+port normalisation to a separate package to make it easier to reuse this functionality in other repositories.

### CODE REVIEW

**Review by jjiang-stripe — APPROVED** [review]
This is a much cleaner interface! I confirmed that we're pretty much just re-using existing code (with a couple more helpers defined), so there should be no change in behaviour.

**Comment by jjiang-stripe** [comment]
ah there's one failing test because we use `%q` in an error message

**Review by jjiang-stripe — CHANGES_REQUESTED** [review]
i can re-approve once we fix that test!

**Comment by lewandowski-stripe** [comment]
> i can re-approve once we fix that test!

Done. Sorry about the failing tests, I had to rush the PR out of the door before I disappeared for the weekend.

**Review by jjiang-stripe — APPROVED** [review]

**Pull request merged**
